<a href="https://colab.research.google.com/github/naswadani/kripto/blob/main/DES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import secrets

plain_text = input("Masukan PlainText = ")
ascii_list = [ord(char) for char in plain_text]
binary_list = [format(angka, '08b')for angka in ascii_list]
hex_key = secrets.token_hex(8)
print("Bentuk Hex Key = ",hex_key )
print("Bentuk ASCII   = ",ascii_list)
print("Bentuk Binary  = ",binary_list)

Masukan PlainText = naswabrynadanikhansa
Bentuk Hex Key =  4b965d232c8f0ea3
Bentuk ASCII   =  [110, 97, 115, 119, 97, 98, 114, 121, 110, 97, 100, 97, 110, 105, 107, 104, 97, 110, 115, 97]
Bentuk Binary  =  ['01101110', '01100001', '01110011', '01110111', '01100001', '01100010', '01110010', '01111001', '01101110', '01100001', '01100100', '01100001', '01101110', '01101001', '01101011', '01101000', '01100001', '01101110', '01110011', '01100001']


In [2]:
def printArr(arr):
  num = 1
  for i in arr:
    print(num,i)
    num += 1

In [3]:
array_plaintext_awal = []
counter = 1
for i in range(8):
  new_array = []
  for i in range(8):
    new_array.append(counter)
    counter+=1
  array_plaintext_awal.append(new_array)
print("Urutan bit Plaintext awal : ")
printArr(array_plaintext_awal)

Urutan bit Plaintext awal : 
1 [1, 2, 3, 4, 5, 6, 7, 8]
2 [9, 10, 11, 12, 13, 14, 15, 16]
3 [17, 18, 19, 20, 21, 22, 23, 24]
4 [25, 26, 27, 28, 29, 30, 31, 32]
5 [33, 34, 35, 36, 37, 38, 39, 40]
6 [41, 42, 43, 44, 45, 46, 47, 48]
7 [49, 50, 51, 52, 53, 54, 55, 56]
8 [57, 58, 59, 60, 61, 62, 63, 64]


In [4]:
array_permutasi_awal = []
def acak_plaintext_array(pembagi):
  con = 0
  for i in range(len(array_plaintext_awal)):
    con += 1
    arr = []
    for j in range(7,-1,-1):
      if(con % 2 == pembagi):
        arr.append(array_plaintext_awal[j][i])
      else:
        continue
    if(con % 2 == pembagi):
      array_permutasi_awal.append(arr)

In [5]:
for i in range(2):
  acak_plaintext_array(i)

print("Urutan bit Permutasi awal : ")
printArr(array_permutasi_awal)

Urutan bit Permutasi awal : 
1 [58, 50, 42, 34, 26, 18, 10, 2]
2 [60, 52, 44, 36, 28, 20, 12, 4]
3 [62, 54, 46, 38, 30, 22, 14, 6]
4 [64, 56, 48, 40, 32, 24, 16, 8]
5 [57, 49, 41, 33, 25, 17, 9, 1]
6 [59, 51, 43, 35, 27, 19, 11, 3]
7 [61, 53, 45, 37, 29, 21, 13, 5]
8 [63, 55, 47, 39, 31, 23, 15, 7]


In [6]:
while len(binary_list) % 8 != 0:
    binary_list.append('0' * 8)
array_encoding_IP = []
for i in binary_list:
  sub_arr_encoding_IP = []
  for j in array_permutasi_awal:
    for k in j :
       if k <= len(i):
        char = i[k-1]
        sub_arr_encoding_IP.append(char)
  array_encoding_IP.append(sub_arr_encoding_IP)

print("Hasil Encoding IP :")
printArr(array_encoding_IP)

Hasil Encoding IP :
1 ['1', '0', '1', '0', '0', '1', '1', '1']
2 ['1', '0', '0', '1', '0', '1', '0', '0']
3 ['1', '1', '0', '1', '0', '1', '0', '1']
4 ['1', '1', '1', '1', '0', '1', '0', '1']
5 ['1', '0', '0', '1', '0', '1', '0', '0']
6 ['1', '0', '0', '0', '0', '1', '0', '1']
7 ['1', '1', '0', '0', '0', '1', '0', '1']
8 ['1', '1', '0', '1', '0', '1', '1', '0']
9 ['1', '0', '1', '0', '0', '1', '1', '1']
10 ['1', '0', '0', '1', '0', '1', '0', '0']
11 ['1', '0', '1', '0', '0', '1', '0', '0']
12 ['1', '0', '0', '1', '0', '1', '0', '0']
13 ['1', '0', '1', '0', '0', '1', '1', '1']
14 ['1', '0', '0', '1', '0', '1', '1', '0']
15 ['1', '0', '0', '1', '0', '1', '1', '1']
16 ['1', '0', '0', '0', '0', '1', '1', '0']
17 ['1', '0', '0', '1', '0', '1', '0', '0']
18 ['1', '0', '1', '0', '0', '1', '1', '1']
19 ['1', '1', '0', '1', '0', '1', '0', '1']
20 ['1', '0', '0', '1', '0', '1', '0', '0']
21 ['0', '0', '0', '0', '0', '0', '0', '0']
22 ['0', '0', '0', '0', '0', '0', '0', '0']
23 ['0', '0', '0', '0

In [103]:
panjang_arr = len(array_encoding_IP)
middle_index = panjang_arr//2
Lo = array_encoding_IP[:middle_index]
Ro = array_encoding_IP[middle_index:]
RoStr = ""
for sub in Ro:
  RoStr += ''.join(sub)
print("Lo : ")
printArr(Lo)
print("\nRo : ")
printArr(Ro)


Lo : 
1 ['1', '0', '1', '0', '0', '1', '1', '1']
2 ['1', '0', '0', '1', '0', '1', '0', '0']
3 ['1', '1', '0', '1', '0', '1', '0', '1']
4 ['1', '1', '1', '1', '0', '1', '0', '1']
5 ['1', '0', '0', '1', '0', '1', '0', '0']
6 ['1', '0', '0', '0', '0', '1', '0', '1']
7 ['1', '1', '0', '0', '0', '1', '0', '1']
8 ['1', '1', '0', '1', '0', '1', '1', '0']
9 ['1', '0', '1', '0', '0', '1', '1', '1']
10 ['1', '0', '0', '1', '0', '1', '0', '0']
11 ['1', '0', '1', '0', '0', '1', '0', '0']
12 ['1', '0', '0', '1', '0', '1', '0', '0']

Ro : 
1 ['1', '0', '1', '0', '0', '1', '1', '1']
2 ['1', '0', '0', '1', '0', '1', '1', '0']
3 ['1', '0', '0', '1', '0', '1', '1', '1']
4 ['1', '0', '0', '0', '0', '1', '1', '0']
5 ['1', '0', '0', '1', '0', '1', '0', '0']
6 ['1', '0', '1', '0', '0', '1', '1', '1']
7 ['1', '1', '0', '1', '0', '1', '0', '1']
8 ['1', '0', '0', '1', '0', '1', '0', '0']
9 ['0', '0', '0', '0', '0', '0', '0', '0']
10 ['0', '0', '0', '0', '0', '0', '0', '0']
11 ['0', '0', '0', '0', '0', '0', '0'

In [8]:
tabelpc1=[[57,49,41,33,25,17,9],
          [1,58,50,42,34,26,18],
          [10,2,59,51,43,35,27],
          [19,11,3,60,52,44,36],
          [63,55,47,39,31,23,15],
          [7,62,54,46,38,30,22],
          [14,6,61,53,45,37,29],
          [21,13,5,28,20,12,4]]
#menjadikan string hex dari key menjadi array
arr_key= []
for i in range(8):
  sub_arr = hex_key[i * 2 : (i + 1)*2]
  arr_key.append(sub_arr)
print(arr_key)

['4b', '96', '5d', '23', '2c', '8f', '0e', 'a3']


In [9]:
def heksadesimal_ke_biner(heks_string):
    panjang_biner = len(heks_string) * 4
    biner_string = bin(int(heks_string, 16))[2:].zfill(panjang_biner)
    return biner_string

In [10]:
arr_key_biner = []
#merubah bentuk hex menjadi biner
for hex_string in arr_key:
  biner_str = heksadesimal_ke_biner(hex_string)
  arr_key_biner.append(biner_str)

print(arr_key_biner)

['01001011', '10010110', '01011101', '00100011', '00101100', '10001111', '00001110', '10100011']


In [11]:
string_key_biner = ''.join(arr_key_biner)
array_permutasi_PC1 = []
for i in tabelpc1:
  for j in i:
      if j <= len(string_key_biner):
        chara = string_key_biner[j-1]
        array_permutasi_PC1.append(chara)

Kplus = ''.join(array_permutasi_PC1)
print("K+ = ",Kplus)
Str_Co = Kplus[:28]
Str_Do = Kplus[28:]
print("Co = ",Str_Co)
print("Do = ",Str_Do)

K+ =  10100010000001011001100000001110101101110110011101010110
Co =  1010001000000101100110000000
Do =  1110101101110110011101010110


In [12]:
tabelWrapping = [1,1,2,2,2,2,2,2,1,2,2,2,2,2,2,1]
Co = []
Do = []
for char in Str_Co:
  Co.append(char)
for char in Str_Do:
  Do.append(char)

In [13]:
C = []
D = []
nomer = 1

print("C0","\t= ",Co,sep='')
print("D0","\t= ",Do,sep='')
print("")
#melakukan pergesearn sesuai dengan yang ada pada tabel wrapping
for move in tabelWrapping:
    move = move % len(Co)
    Do = Do[move:] + Do[:move]
    Co = Co[move:] + Co[:move]
    C.append(Co)
    D.append(Do)

for i in range(0,16):
  print("C",nomer,"\t= ",C[i],sep='')
  print("D",nomer,"\t= ",D[i],sep='')
  print("")
  nomer+=1


C0	= ['1', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0']
D0	= ['1', '1', '1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0']

C1	= ['0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1']
D1	= ['1', '1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1']

C2	= ['1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0']
D2	= ['1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1', '1']

C3	= ['0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', 

In [14]:
CoDo = []

# Pengabungan antara Cx dan Dx
for sub_C, sub_D in zip(C, D):
    array_gabungan = sub_C + sub_D
    CoDo.append(array_gabungan)

# Mencetak hasil penggabungan
num = 1
for arr in CoDo:
    print("C",num,"D",num,"\t= ",arr,sep='')
    num+=1



C1D1	= ['0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1']
C2D2	= ['1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1', '1']
C3D3	= ['0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0']
C4D4	= ['1', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0'

In [15]:
tabelpc2 = [[14,17,11,24,1,5],
            [3,28,15,6,21,10],
            [23,19,12,4,26,8],
            [16,7,27,20,13,2],
            [41,52,31,37,47,55],
            [30,40,51,45,33,48],
            [44,49,39,56,34,53],
            [46,42,50,36,29,32]]

In [16]:
K = [] #mutasi dengan tabel PC-2
for sub_arr in CoDo:
  sub_array_K = []
  for arr in tabelpc2:
    for i in arr:
      char = sub_arr[i-1]
      sub_array_K.append(char)
  K.append(sub_array_K)


In [17]:
num = 1 #hasil dari permutasi dengan tabel PC-2
print("Key Hasil PC-2")
for arr in K:
    print("K",num,"\t= ",arr,sep='')
    num+=1

Key Hasil PC-2
K1	= ['0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1', '1', '1', '1', '0', '0', '1', '1', '0', '1', '0', '1', '1', '0', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '0', '1', '1']
K2	= ['1', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '1', '1', '0', '1', '1', '1', '0']
K3	= ['0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', '1', '0', '0', '1', '0', '0', '1', '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1']
K4	= ['1', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '1', '0', '1', '0', '1', '1', '1', '1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '1', '1', '0', '1', '1', '1']
K

In [88]:
#tabel ekspansi
import numpy as np
tabel_ekspansi = []
Number = 1
for i in range(len(Ro)):
  sub_eks = []
  for j in range(len(Ro[i])):
    num = Number
    sub_eks.append(num)
    Number += 1
  tabel_ekspansi.append(sub_eks)

print("Tabel Ekspansi")

left_side = []
right_side = []


for subarray in tabel_ekspansi:
    last_element = subarray[-1]  # Mengambil elemen terakhir dari setiap subarray
    left_side.append(last_element)

left_side.insert(0, left_side.pop())

for subarray in tabel_ekspansi:
  first_element = subarray[0]  # Mengambil elemen pertama dari setiap subarray
  right_side.append(first_element)

right_side = right_side[1:] + [right_side[0]]

left_side = np.array(left_side)
right_side = np.array(right_side)
tabel_ekspansi = np.hstack((left_side.reshape(12,1),tabel_ekspansi))
tabel_ekspansi = np.hstack((tabel_ekspansi,right_side.reshape(12,1)))
print(tabel_ekspansi)


Tabel Ekspansi
[[96  1  2  3  4  5  6  7  8  9]
 [ 8  9 10 11 12 13 14 15 16 17]
 [16 17 18 19 20 21 22 23 24 25]
 [24 25 26 27 28 29 30 31 32 33]
 [32 33 34 35 36 37 38 39 40 41]
 [40 41 42 43 44 45 46 47 48 49]
 [48 49 50 51 52 53 54 55 56 57]
 [56 57 58 59 60 61 62 63 64 65]
 [64 65 66 67 68 69 70 71 72 73]
 [72 73 74 75 76 77 78 79 80 81]
 [80 81 82 83 84 85 86 87 88 89]
 [88 89 90 91 92 93 94 95 96  1]]


In [108]:
ER = [] #mutasi dengan tabel PC-2
for i in tabel_ekspansi:
  sub_arr_ER = []
  for j in i:
    char = RoStr[j-1]
    sub_arr_ER.append(char)
  ER.append(sub_arr_ER)

printArr(ER)

1 ['0', '1', '0', '1', '0', '0', '1', '1', '1', '1']
2 ['1', '1', '0', '0', '1', '0', '1', '1', '0', '1']
3 ['0', '1', '0', '0', '1', '0', '1', '1', '1', '1']
4 ['1', '1', '0', '0', '0', '0', '1', '1', '0', '1']
5 ['0', '1', '0', '0', '1', '0', '1', '0', '0', '1']
6 ['0', '1', '0', '1', '0', '0', '1', '1', '1', '1']
7 ['1', '1', '1', '0', '1', '0', '1', '0', '1', '1']
8 ['1', '1', '0', '0', '1', '0', '1', '0', '0', '0']
9 ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
10 ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
11 ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
12 ['0', '0', '0', '0', '0', '0', '0', '0', '0', '1']
